#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def solution(max):
	prev_two = 1
	prev_one = 2
	curr = 0
	total = 2 #include the original 2
	while(curr < max):
		curr = prev_one + prev_two
		if (curr % 2 == 0):
			total = total + curr
		prev_two = prev_one
		prev_one = curr
	print(total)
	return total

if(solution(4000000) == 4613732):
	print("Working")
